# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(900, 600)
        MainWindow.setMinimumSize(QtCore.QSize(900, 600))
        MainWindow.setMaximumSize(QtCore.QSize(900, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ser_list = QtWidgets.QComboBox(self.centralwidget)
        self.ser_list.setGeometry(QtCore.QRect(10, 30, 351, 32))
        self.ser_list.setStyleSheet("QComboBox {\n"
"    border: 1px solid rgba(204, 204, 204, 0.8);\n"
"    border-radius: 8px;\n"
"    background-color: rgba(255, 255, 255, 0.8);\n"
"    padding: 5px 25px 5px 10px; /* 右侧留出下拉按钮空间 */\n"
"    min-height: 20px;\n"
"    selection-background-color: rgba(100, 149, 237, 0.8); /* 选中项背景 */\n"
"}\n"
"\n"
"/* 下拉按钮 */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left: 1px solid rgba(204, 204, 204, 0.8);\n"
"    border-radius: 0 8px 8px 0;\n"
"}\n"
"\n"
"/* 下拉箭头 */\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/arrow_down.png); /* 可以自定义箭头 */\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"/* 鼠标悬停在按钮上 */\n"
"QComboBox::drop-down:hover {\n"
"    background-color: rgba(230, 230, 230, 0.8);\n"
"}\n"
"\n"
"/* 下拉列表视图 */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid rgba(204, 204, 204, 0.8);\n"
"    border-radius: 8px;\n"
"    background-color: rgba(255, 255, 255, 0.9); /* 下拉列表背景 */\n"
"    selection-background-color: rgba(100, 149, 237, 0.8);\n"
"    outline: none; /* 移除焦点虚线框 */\n"
"}\n"
"\n"
"/* 下拉列表中的项 */\n"
"QComboBox QAbstractItemView::item {\n"
"    height: 25px;\n"
"    padding: 5px;\n"
"    color: rgba(0, 0, 0, 0.8);\n"
"}\n"
"\n"
"/* 下拉列表中的项 - 悬停 */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: rgba(240, 240, 240, 0.7);\n"
"}")
        self.ser_list.setObjectName("ser_list")
        self.ser_con = QtWidgets.QPushButton(self.centralwidget)
        self.ser_con.setGeometry(QtCore.QRect(470, 70, 131, 51))
        self.ser_con.setStyleSheet("QPushButton {\n"
"    font: 9pt \"幼圆\";\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 10px;\n"
"    background-color: rgba(240, 240, 240, 0.6); /* #f0f0f0 转 rgba，50%透明度 */\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"}")
        self.ser_con.setObjectName("ser_con")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 0, 121, 31))
        self.label.setStyleSheet("font: 20pt \"幼圆\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 81, 31))
        self.label_2.setStyleSheet("font: 12pt \"幼圆\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 60, 81, 31))
        self.label_3.setStyleSheet("font: 12pt \"幼圆\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 54, 16))
        self.label_4.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 54, 16))
        self.label_5.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_5.setObjectName("label_5")
        self.H = QtWidgets.QLabel(self.centralwidget)
        self.H.setGeometry(QtCore.QRect(90, 60, 111, 31))
        self.H.setStyleSheet("font: 12pt \"幼圆\";")
        self.H.setObjectName("H")
        self.D = QtWidgets.QLabel(self.centralwidget)
        self.D.setGeometry(QtCore.QRect(280, 60, 111, 31))
        self.D.setStyleSheet("font: 12pt \"幼圆\";")
        self.D.setObjectName("D")
        self.band_rate = QtWidgets.QComboBox(self.centralwidget)
        self.band_rate.setGeometry(QtCore.QRect(480, 30, 111, 32))
        self.band_rate.setStyleSheet("QComboBox {\n"
"    border: 1px solid rgba(204, 204, 204, 0.8);\n"
"    border-radius: 8px;\n"
"    background-color: rgba(255, 255, 255, 0.8);\n"
"    padding: 5px 25px 5px 10px; /* 右侧留出下拉按钮空间 */\n"
"    min-height: 20px;\n"
"    selection-background-color: rgba(100, 149, 237, 0.8); /* 选中项背景 */\n"
"}\n"
"\n"
"/* 下拉按钮 */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left: 1px solid rgba(204, 204, 204, 0.8);\n"
"    border-radius: 0 8px 8px 0;\n"
"}\n"
"\n"
"/* 下拉箭头 */\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/arrow_down.png); /* 可以自定义箭头 */\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"/* 鼠标悬停在按钮上 */\n"
"QComboBox::drop-down:hover {\n"
"    background-color: rgba(230, 230, 230, 0.8);\n"
"}\n"
"\n"
"/* 下拉列表视图 */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid rgba(204, 204, 204, 0.8);\n"
"    border-radius: 8px;\n"
"    background-color: rgba(255, 255, 255, 0.9); /* 下拉列表背景 */\n"
"    selection-background-color: rgba(100, 149, 237, 0.8);\n"
"    outline: none; /* 移除焦点虚线框 */\n"
"}\n"
"\n"
"/* 下拉列表中的项 */\n"
"QComboBox QAbstractItemView::item {\n"
"    height: 25px;\n"
"    padding: 5px;\n"
"    color: rgba(0, 0, 0, 0.8);\n"
"}\n"
"\n"
"/* 下拉列表中的项 - 悬停 */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: rgba(240, 240, 240, 0.7);\n"
"}")
        self.band_rate.setObjectName("band_rate")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(500, 0, 101, 31))
        self.label_6.setStyleSheet("font: 16pt \"幼圆\";")
        self.label_6.setObjectName("label_6")
        self.TX = QtWidgets.QLabel(self.centralwidget)
        self.TX.setGeometry(QtCore.QRect(50, 90, 311, 16))
        self.TX.setStyleSheet("font: 10pt \"幼圆\";")
        self.TX.setObjectName("TX")
        self.RX = QtWidgets.QLabel(self.centralwidget)
        self.RX.setGeometry(QtCore.QRect(50, 110, 311, 16))
        self.RX.setStyleSheet("font: 10pt \"幼圆\";")
        self.RX.setObjectName("RX")
        self.star_plot = QtWidgets.QWidget(self.centralwidget)
        self.star_plot.setGeometry(QtCore.QRect(10, 130, 421, 421))
        self.star_plot.setStyleSheet("QWidget#star_plot {\n"
"    background-color: rgba(255, 255, 255, 0.2);\n"
"    border: 2px solid rgba(100, 100, 100, 0.5);\n"
"    border-radius: 5px;\n"
"}")
        self.star_plot.setObjectName("star_plot")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(600, 10, 20, 541))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(620, 0, 151, 41))
        self.label_7.setStyleSheet("font: 20pt \"幼圆\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(620, 70, 151, 41))
        self.label_8.setStyleSheet("font: 20pt \"幼圆\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(620, 110, 151, 41))
        self.label_9.setStyleSheet("font: 20pt \"幼圆\";")
        self.label_9.setObjectName("label_9")
        self.track_name = QtWidgets.QLabel(self.centralwidget)
        self.track_name.setGeometry(QtCore.QRect(620, 40, 281, 31))
        self.track_name.setStyleSheet("font: 18pt \"EuroRoman\";\n"
"color: rgb(255, 0, 0);")
        self.track_name.setObjectName("track_name")
        self.track_h = QtWidgets.QLabel(self.centralwidget)
        self.track_h.setGeometry(QtCore.QRect(780, 80, 281, 31))
        self.track_h.setStyleSheet("font: 18pt \"EuroRoman\";\n"
"color: rgb(255, 0, 0);")
        self.track_h.setObjectName("track_h")
        self.track_d = QtWidgets.QLabel(self.centralwidget)
        self.track_d.setGeometry(QtCore.QRect(780, 120, 281, 31))
        self.track_d.setStyleSheet("font: 18pt \"EuroRoman\";\n"
"color: rgb(255, 0, 0);")
        self.track_d.setObjectName("track_d")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(620, 230, 271, 41))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.track_c = QtWidgets.QPushButton(self.centralwidget)
        self.track_c.setGeometry(QtCore.QRect(630, 160, 241, 81))
        self.track_c.setStyleSheet("QPushButton {\n"
"    font: 9pt \"幼圆\";\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 10px;\n"
"    background-color: rgba(240, 240, 240, 0.6); /* #f0f0f0 转 rgba，50%透明度 */\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"}")
        self.track_c.setObjectName("track_c")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(710, 250, 121, 41))
        self.label_10.setStyleSheet("font: 20pt \"幼圆\";")
        self.label_10.setObjectName("label_10")
        self.up = QtWidgets.QPushButton(self.centralwidget)
        self.up.setGeometry(QtCore.QRect(750, 290, 31, 81))
        self.up.setStyleSheet("QPushButton {\n"
"    /* 深灰基础样式 */\n"
"    border: 1px solid rgba(80, 80, 80, 0.6);\n"
"    border-radius: 6px;\n"
"    background-color: rgba(90, 90, 90, 0.6);\n"
"    color: #e0e0e0;\n"
"    padding: 8px 16px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid rgba(100, 100, 100, 0.6);\n"
"    background-color: rgba(110, 110, 110, 0.6);\n"
"    color: #f0f0f0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 1px solid rgba(70, 70, 70, 1);\n"
"    background-color: rgba(130, 130, 130, 0.7);\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    border: 1px solid rgba(60, 60, 60, 0.5);\n"
"    background-color: rgba(70, 70, 70, 0.3);\n"
"    color: rgba(150, 150, 150, 0.7);\n"
"}")
        self.up.setText("")
        self.up.setObjectName("up")
        self.down = QtWidgets.QPushButton(self.centralwidget)
        self.down.setGeometry(QtCore.QRect(750, 460, 31, 81))
        self.down.setStyleSheet("QPushButton {\n"
"    /* 深灰基础样式 */\n"
"    border: 1px solid rgba(80, 80, 80, 0.6);\n"
"    border-radius: 6px;\n"
"    background-color: rgba(90, 90, 90, 0.6);\n"
"    color: #e0e0e0;\n"
"    padding: 8px 16px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid rgba(100, 100, 100, 0.6);\n"
"    background-color: rgba(110, 110, 110, 0.6);\n"
"    color: #f0f0f0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 1px solid rgba(70, 70, 70, 1);\n"
"    background-color: rgba(130, 130, 130, 0.7);\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    border: 1px solid rgba(60, 60, 60, 0.5);\n"
"    background-color: rgba(70, 70, 70, 0.3);\n"
"    color: rgba(150, 150, 150, 0.7);\n"
"}")
        self.down.setText("")
        self.down.setObjectName("down")
        self.right = QtWidgets.QPushButton(self.centralwidget)
        self.right.setGeometry(QtCore.QRect(810, 400, 81, 31))
        self.right.setStyleSheet("QPushButton {\n"
"    /* 深灰基础样式 */\n"
"    border: 1px solid rgba(80, 80, 80, 0.6);\n"
"    border-radius: 6px;\n"
"    background-color: rgba(90, 90, 90, 0.6);\n"
"    color: #e0e0e0;\n"
"    padding: 8px 16px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid rgba(100, 100, 100, 0.6);\n"
"    background-color: rgba(110, 110, 110, 0.6);\n"
"    color: #f0f0f0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 1px solid rgba(70, 70, 70, 1);\n"
"    background-color: rgba(130, 130, 130, 0.7);\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    border: 1px solid rgba(60, 60, 60, 0.5);\n"
"    background-color: rgba(70, 70, 70, 0.3);\n"
"    color: rgba(150, 150, 150, 0.7);\n"
"}")
        self.right.setText("")
        self.right.setObjectName("right")
        self.left = QtWidgets.QPushButton(self.centralwidget)
        self.left.setGeometry(QtCore.QRect(640, 400, 81, 31))
        self.left.setStyleSheet("QPushButton {\n"
"    /* 深灰基础样式 */\n"
"    border: 1px solid rgba(80, 80, 80, 0.6);\n"
"    border-radius: 6px;\n"
"    background-color: rgba(90, 90, 90, 0.6);\n"
"    color: #e0e0e0;\n"
"    padding: 8px 16px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid rgba(100, 100, 100, 0.6);\n"
"    background-color: rgba(110, 110, 110, 0.6);\n"
"    color: #f0f0f0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 1px solid rgba(70, 70, 70, 1);\n"
"    background-color: rgba(130, 130, 130, 0.7);\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    border: 1px solid rgba(60, 60, 60, 0.5);\n"
"    background-color: rgba(70, 70, 70, 0.3);\n"
"    color: rgba(150, 150, 150, 0.7);\n"
"}")
        self.left.setText("")
        self.left.setObjectName("left")
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(740, 390, 51, 51))
        self.stop.setStyleSheet("QPushButton {\n"
"    /* 深灰基础样式 */\n"
"    border: 1px solid rgba(80, 80, 80, 0.6);\n"
"    border-radius: 6px;\n"
"    background-color: rgba(90, 90, 90, 0.6);\n"
"    color: #e0e0e0;\n"
"    padding: 8px 11px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid rgba(100, 100, 100, 0.6);\n"
"    background-color: rgba(110, 110, 110, 0.6);\n"
"    color: #f0f0f0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 1px solid rgba(70, 70, 70, 1);\n"
"    background-color: rgba(130, 130, 130, 0.7);\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    border: 1px solid rgba(60, 60, 60, 0.5);\n"
"    background-color: rgba(70, 70, 70, 0.3);\n"
"    color: rgba(150, 150, 150, 0.7);\n"
"}")
        self.stop.setObjectName("stop")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(440, 370, 31, 31))
        self.frame.setStyleSheet("border-radius: 50%;\n"
"color: rgb(0, 0, 255);\n"
"background-color: rgb(0, 0, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(440, 410, 31, 31))
        self.frame_2.setStyleSheet("border-radius: 50%;\n"
"background-color: rgb(255, 0, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(480, 370, 101, 31))
        self.label_11.setStyleSheet("font: 16pt \"幼圆\";")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(480, 410, 91, 31))
        self.label_12.setStyleSheet("font: 16pt \"幼圆\";")
        self.label_12.setObjectName("label_12")
        self.h_in = QtWidgets.QLineEdit(self.centralwidget)
        self.h_in.setGeometry(QtCore.QRect(630, 300, 101, 21))
        self.h_in.setStyleSheet("QLineEdit {\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    padding: 0 8px;\n"
"    background-color: rgba(255, 255, 255, 0.7); /* 最后一个参数是透明度，0-1 */\n"
"}")
        self.h_in.setObjectName("h_in")
        self.d_in = QtWidgets.QLineEdit(self.centralwidget)
        self.d_in.setGeometry(QtCore.QRect(630, 350, 101, 20))
        self.d_in.setStyleSheet("QLineEdit {\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    padding: 0 8px;\n"
"    background-color: rgba(255, 255, 255, 0.7); /* 最后一个参数是透明度，0-1 */\n"
"}")
        self.d_in.setObjectName("d_in")
        self.run_set = QtWidgets.QPushButton(self.centralwidget)
        self.run_set.setGeometry(QtCore.QRect(800, 310, 75, 51))
        self.run_set.setStyleSheet("QPushButton {\n"
"    font: 9pt \"幼圆\";\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 10px;\n"
"    background-color: rgba(240, 240, 240, 0.6); /* #f0f0f0 转 rgba，50%透明度 */\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"}")
        self.run_set.setObjectName("run_set")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(630, 320, 91, 31))
        self.label_14.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(630, 270, 81, 31))
        self.label_15.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_15.setObjectName("label_15")
        self.address = QtWidgets.QLineEdit(self.centralwidget)
        self.address.setGeometry(QtCore.QRect(200, 90, 71, 31))
        self.address.setStyleSheet("QLineEdit {\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    padding: 0 8px;\n"
"    background-color: rgba(255, 255, 255, 0.7); /* 最后一个参数是透明度，0-1 */\n"
"}")
        self.address.setObjectName("address")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(280, 90, 81, 31))
        self.label_13.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_13.setObjectName("label_13")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(440, 440, 81, 31))
        self.label_16.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_16.setObjectName("label_16")
        self.status_color = QtWidgets.QFrame(self.centralwidget)
        self.status_color.setGeometry(QtCore.QRect(440, 470, 31, 31))
        self.status_color.setStyleSheet("border-radius: 50%;\n"
"background-color: rgb(255, 0, 0);")
        self.status_color.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_color.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status_color.setObjectName("status_color")
        self.status_text = QtWidgets.QLabel(self.centralwidget)
        self.status_text.setGeometry(QtCore.QRect(480, 460, 71, 51))
        self.status_text.setStyleSheet("font: 16pt \"幼圆\";")
        self.status_text.setObjectName("status_text")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(0, 0, 900, 600))
        self.label_17.setMinimumSize(QtCore.QSize(900, 600))
        self.label_17.setMaximumSize(QtCore.QSize(900, 600))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("background.png"))
        self.label_17.setObjectName("label_17")
        self.h_delta = QtWidgets.QLineEdit(self.centralwidget)
        self.h_delta.setGeometry(QtCore.QRect(370, 30, 91, 31))
        self.h_delta.setStyleSheet("QLineEdit {\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    padding: 0 8px;\n"
"    background-color: rgba(255, 255, 255, 0.7); /* 最后一个参数是透明度，0-1 */\n"
"}")
        self.h_delta.setObjectName("h_delta")
        self.d_delta = QtWidgets.QLineEdit(self.centralwidget)
        self.d_delta.setGeometry(QtCore.QRect(370, 90, 91, 31))
        self.d_delta.setStyleSheet("QLineEdit {\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    padding: 0 8px;\n"
"    background-color: rgba(255, 255, 255, 0.7); /* 最后一个参数是透明度，0-1 */\n"
"}")
        self.d_delta.setObjectName("d_delta")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(370, 0, 81, 31))
        self.label_18.setStyleSheet("font: 12pt \"幼圆\";")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(370, 60, 81, 31))
        self.label_19.setStyleSheet("font: 12pt \"幼圆\";")
        self.label_19.setObjectName("label_19")
        self.angle_cycle = QtWidgets.QLineEdit(self.centralwidget)
        self.angle_cycle.setGeometry(QtCore.QRect(440, 210, 91, 31))
        self.angle_cycle.setStyleSheet("QLineEdit {\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    padding: 0 8px;\n"
"    background-color: rgba(255, 255, 255, 0.7); /* 最后一个参数是透明度，0-1 */\n"
"}")
        self.angle_cycle.setObjectName("angle_cycle")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(440, 180, 131, 31))
        self.label_20.setStyleSheet("font: 12pt \"幼圆\";")
        self.label_20.setObjectName("label_20")
        self.task_cycle = QtWidgets.QLineEdit(self.centralwidget)
        self.task_cycle.setGeometry(QtCore.QRect(440, 270, 91, 31))
        self.task_cycle.setStyleSheet("QLineEdit {\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    padding: 0 8px;\n"
"    background-color: rgba(255, 255, 255, 0.7); /* 最后一个参数是透明度，0-1 */\n"
"}")
        self.task_cycle.setObjectName("task_cycle")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(440, 240, 131, 31))
        self.label_21.setStyleSheet("font: 12pt \"幼圆\";")
        self.label_21.setObjectName("label_21")
        self.angle_if = QtWidgets.QComboBox(self.centralwidget)
        self.angle_if.setGeometry(QtCore.QRect(440, 150, 91, 32))
        self.angle_if.setStyleSheet("QComboBox {\n"
"    border: 1px solid rgba(204, 204, 204, 0.8);\n"
"    border-radius: 8px;\n"
"    background-color: rgba(255, 255, 255, 0.8);\n"
"    padding: 5px 25px 5px 10px; /* 右侧留出下拉按钮空间 */\n"
"    min-height: 20px;\n"
"    selection-background-color: rgba(100, 149, 237, 0.8); /* 选中项背景 */\n"
"}\n"
"\n"
"/* 下拉按钮 */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left: 1px solid rgba(204, 204, 204, 0.8);\n"
"    border-radius: 0 8px 8px 0;\n"
"}\n"
"\n"
"/* 下拉箭头 */\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/arrow_down.png); /* 可以自定义箭头 */\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"/* 鼠标悬停在按钮上 */\n"
"QComboBox::drop-down:hover {\n"
"    background-color: rgba(230, 230, 230, 0.8);\n"
"}\n"
"\n"
"/* 下拉列表视图 */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid rgba(204, 204, 204, 0.8);\n"
"    border-radius: 8px;\n"
"    background-color: rgba(255, 255, 255, 0.9); /* 下拉列表背景 */\n"
"    selection-background-color: rgba(100, 149, 237, 0.8);\n"
"    outline: none; /* 移除焦点虚线框 */\n"
"}\n"
"\n"
"/* 下拉列表中的项 */\n"
"QComboBox QAbstractItemView::item {\n"
"    height: 25px;\n"
"    padding: 5px;\n"
"    color: rgba(0, 0, 0, 0.8);\n"
"}\n"
"\n"
"/* 下拉列表中的项 - 悬停 */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: rgba(240, 240, 240, 0.7);\n"
"}")
        self.angle_if.setObjectName("angle_if")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(440, 120, 111, 31))
        self.label_22.setStyleSheet("font: 12pt \"幼圆\";")
        self.label_22.setObjectName("label_22")
        self.angle_resolution = QtWidgets.QLineEdit(self.centralwidget)
        self.angle_resolution.setGeometry(QtCore.QRect(440, 330, 91, 31))
        self.angle_resolution.setStyleSheet("QLineEdit {\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    padding: 0 8px;\n"
"    background-color: rgba(255, 255, 255, 0.7); /* 最后一个参数是透明度，0-1 */\n"
"}")
        self.angle_resolution.setObjectName("angle_resolution")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(440, 300, 131, 31))
        self.label_23.setStyleSheet("font: 12pt \"幼圆\";")
        self.label_23.setObjectName("label_23")
        self.label_17.raise_()
        self.ser_list.raise_()
        self.ser_con.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.H.raise_()
        self.D.raise_()
        self.band_rate.raise_()
        self.label_6.raise_()
        self.TX.raise_()
        self.RX.raise_()
        self.star_plot.raise_()
        self.line.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.track_name.raise_()
        self.track_h.raise_()
        self.track_d.raise_()
        self.line_2.raise_()
        self.track_c.raise_()
        self.label_10.raise_()
        self.up.raise_()
        self.down.raise_()
        self.right.raise_()
        self.left.raise_()
        self.stop.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.h_in.raise_()
        self.d_in.raise_()
        self.run_set.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.address.raise_()
        self.label_13.raise_()
        self.label_16.raise_()
        self.status_color.raise_()
        self.status_text.raise_()
        self.h_delta.raise_()
        self.d_delta.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.angle_cycle.raise_()
        self.label_20.raise_()
        self.task_cycle.raise_()
        self.label_21.raise_()
        self.angle_if.raise_()
        self.label_22.raise_()
        self.angle_resolution.raise_()
        self.label_23.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pelco-D云台卫星跟踪程序 By Faecsls(BI1TEU)"))
        self.ser_con.setText(_translate("MainWindow", "打开/关闭串口"))
        self.label.setText(_translate("MainWindow", "串口列表"))
        self.label_2.setText(_translate("MainWindow", "方位角度:"))
        self.label_3.setText(_translate("MainWindow", "俯仰角度:"))
        self.label_4.setText(_translate("MainWindow", "发送:"))
        self.label_5.setText(_translate("MainWindow", "接收:"))
        self.H.setText(_translate("MainWindow", "H"))
        self.D.setText(_translate("MainWindow", "D"))
        self.label_6.setText(_translate("MainWindow", "波特率"))
        self.TX.setText(_translate("MainWindow", "TX"))
        self.RX.setText(_translate("MainWindow", "RX"))
        self.label_7.setText(_translate("MainWindow", "正在跟踪："))
        self.label_8.setText(_translate("MainWindow", "卫星方位角："))
        self.label_9.setText(_translate("MainWindow", "卫星俯仰角："))
        self.track_name.setText(_translate("MainWindow", "0 EXPLORER 11"))
        self.track_h.setText(_translate("MainWindow", "114.5"))
        self.track_d.setText(_translate("MainWindow", "114.5"))
        self.track_c.setText(_translate("MainWindow", "开始/结束跟踪"))
        self.label_10.setText(_translate("MainWindow", "手动控制"))
        self.stop.setText(_translate("MainWindow", "stop"))
        self.label_11.setText(_translate("MainWindow", "卫星位置"))
        self.label_12.setText(_translate("MainWindow", "云台位置"))
        self.run_set.setText(_translate("MainWindow", "设置"))
        self.label_14.setText(_translate("MainWindow", "垂直角设置"))
        self.label_15.setText(_translate("MainWindow", "水平角设置"))
        self.label_13.setText(_translate("MainWindow", "云台地址"))
        self.label_16.setText(_translate("MainWindow", "状态："))
        self.status_text.setText(_translate("MainWindow", "跟踪中"))
        self.label_18.setText(_translate("MainWindow", "方位角度差"))
        self.label_19.setText(_translate("MainWindow", "俯仰角度差"))
        self.label_20.setText(_translate("MainWindow", "角度查询周期(ms)"))
        self.label_21.setText(_translate("MainWindow", "跟踪更新周期(ms)"))
        self.label_22.setText(_translate("MainWindow", "角度查询支持"))
        self.label_23.setText(_translate("MainWindow", "角度分辨率(°)"))
